In [1]:
import numpy as np

In [3]:
a=np.array([0,1]) 
print(a)
b=np.array([1,0]) 
print(b)
np.dot(a,b) 

[0 1]
[1 0]


0

In [8]:
X=np.array([[1,0,1],[2,2,2]]) 
print(X)
out=X[0:2,2]
print(out)
print(X[0:2,1])

[[1 0 1]
 [2 2 2]]
[1 2]
[0 2]


In [10]:
X=np.array([[1,0],[0,1]]) 
print(X)
Y=np.array([[2,1],[1,2]]) 
print(Y)
Z=np.dot(X,Y) 
Z

[[1 0]
 [0 1]]
[[2 1]
 [1 2]]


array([[2, 1],
       [1, 2]])

In [11]:
with open("Example1.txt","r") as file1: 

     file_stuff=file1.readline() 


print(file_stuff) 

This is line 1



In [12]:
with open("Example.txt","a") as writefile: 

       writefile.write("This is line A\n") 

       writefile.write("This is line B\n") 

In [13]:
with open("Example.txt","a") as writefile: 

       writefile.write("This is line C\n") 

       writefile.write("This is line B\n") 

In [14]:
with open("Example3.txt","w") as file1: 

file1.write("This is line C\n") 

<class 'IndentationError'>: expected an indented block after 'with' statement on line 1 (<ipython-input-14-a35de4960d82>, line 3)